language: go
version: tip
sudo: required
services:
  - docker

script:
- make docker_image
- make run
- make deps
- make generate
- make test
- make build
- make stop

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: U8bKOlm83X8ZEw0IgWkW+ANBC7B/33fmkla47SkPd0JaEVNdWf4AlzaKLyLI9+peX/4BD0Le5hClfLzRVuAH+iy65oBHHzs6Oxirl9gUvhbE0890iRaqLMWiLjusVmr4InJoz07W+Xdzf6bsoJZeYDtPM3Qk2Zq2bT3sHKWg7rN7a7l/k1yg4fHYumKRV4zpksopY5vN/7cQQuA/5UarrEZ4dWc2I98MhFPWTc+gTa53wIaPBVMGB5HSTrW11uwSYXCQ666IfHbQiMEODBRrIiBUOWDFDpTJw51QSbwnPMdBep/Ia9XT4QX0PjflmU2HXIx1BEO3g+ppMoTHrdC47V4dK80y9E5JWrLXOH4+UyMTxSco7yok9F4VSzoAT0wR9wiB4fe34HmopgFmLhIlNPn3EIi68/VNHTvDw4go3fy6vFnwxF5Y2B32MGhqAqntyNF97FTxMvRlXchjONU+nVL7Y9mtlV7VwxrVJfG/rRCzM75TGWX/tUXNd/MMvJRu508m6CqyaUY1J9I+i+G+/1FtktV2piLDm4iBLNwPbMvY1jg9qgBdUncdbNh7HJtpOXj8r1aFj04n63jTS0wKOIeAsd+A/F8OQuWa6xd+LfP0B/qN2WgrSsyZD8EjmKQfMr8hCsBt6YI+e6ixR1r8AHeYXvWc9pnPsL3/CIkEpv4=
  file:
    - build/wiki-api.x64
    - build/wiki-crawl.x64
  on:
    tags: true
