language: go
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y wget ca-certificates cmake build-essential
- wget -q https://github.com/libgit2/libgit2/archive/v0.24.1.tar.gz && \
  tar xzf v0.24.1.tar.gz && \
  cd libgit* && \
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DTHREADSAFE=ON && \
  make -j2 && \
  make install

script:
- mkdir build
- go generate -v ./...
- GOOS=linux GOARCH=amd64 go build -v -o build/wiki-api.x64

deploy:
  provider: releases
  api_key:
    secure: cif47/VTlddn/a9R5gCfmuV0nFHZTOsD683K3MlBfW9j8s1vJ0SHGv9LqU64EIODPAw2g04wIbsByT37gCXyIVqFnE8bzjj8Yhk18g0rAUksjthnaRyxzKF/MWvkse3hDvSyjgfpzHiUhnqETYdHwGEk6CGWyQS0twyI7Jq26/HtjD+GPYdAwEvUcembb84mZKoNLBlVnK8HpPFt7ExcxpiGIwwEjFDmzJ1MU9FgQfq95Mn6ZOQgSj5QPnowR2DO0CcQDojZYjYPDr62BshXpRkabeqX4+gnzhUGHsOhaTNpVxR4VYWyA35PCgILJETQS7jldLBBmJSZXOevIJXtiNjJn3Y8ijxgNGOnUsvzl0y82AJ++IkN4nMkiJZGnHXSUA/faGLw5CXJo8Xb4Lt4jmYRxh/NSGJkHBqGVRoBzfFtX6GvY6gVLwUkagS1UiFk8oLytdjXKAkwkuIfTWPhQzK4sNTSiPC5PZQO78AvDOfkwQ4rygRAynkBc8TFv6wKOOCDpyEQfbRZXiNWl0kwXzNVPEiLkASDVE6+flDYaBKb6RP2XqXVm6l7HzQzApvqg53mTXW4j0IWhz5idMERMT1JVAN1GOH+vJrl8Fuw/Ji6RAT6lGSwGrioRRtp+1YXW2ip2PFatq7yWW04abCvX3at44cPoVvPQn6NPzpzySk=
  file: build/wiki-api.x64
  on:
    repo: cfstras/wiki-api
